name = "simply-qr"
compatibility_date = "2024-01-01"
account_id = "c4bea05a1dbc839f100b84241c8120da"

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "simply-qr-db"
database_id = "73d85207-05c8-48e8-aad6-0f4eaa853591"

[[r2_buckets]]
binding = "QR_BUCKET"
bucket_name = "simply-qr"
preview_bucket_name = "simply-qr-preview"
